services:
  postgres:
    image: postgres:alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: diplom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - diplom-app
  redis:
    image: redis:alpine
    container_name: redis-container
    command: ["redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"] # ограничение по памяти
    ports:
      - "6379:6379"
    networks:
      - diplom-app
  server:
    build:
      context: ./server
      network: host
    container_name: server-container
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./server/.env
    volumes:
      - uploads:/usr/src/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - diplom-app
  client:
    build:
      context: ./client
      network: host
    container_name: client-container
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - diplom-app
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - uploads:/usr/src/app/uploads:rw
    depends_on:
      - client
      - server
    networks:
      - diplom-app
networks:
  diplom-app:
    driver: bridge
volumes:
  postgres-data:
  uploads:
