services:
  postgres:
    image: postgres:alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: diplom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - diplom-app

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - diplom-app

  server:
    build:
      context: ./server
    container_name: server-container
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - diplom-app

  client:
    build:
      context: ./client
    container_name: client-container
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - diplom-app

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./server/uploads:/usr/src/app/uploads:ro
    depends_on:
      - client
      - server
    networks:
      - diplom-app

networks:
  diplom-app:
    driver: bridge

volumes:
  postgres-data:
